export const langConfig = {

    ko: {
        name: "한국어",
        title: "한식레시피 aus 독일마트",
        subtitle: "독일 슈퍼마켓에서 쉽게 구할 수 있는 재료로 한식 레시피를 만들어보세요.",
        recent_title: "최근 생성된된 레시피",
        prompt_label: "레시피 아이디어 (예: 두부 + 스페츠레):",
        placeholder: "예시: 소시지와 양배추를 활용한 퓨전 김치볶음밥",
        button_loading: "생성 중...",
        button_ready: "레시피 생성하기 🍚",
        desc_title: "레시피 설명",
        ingredients_title: "재료",
        steps_ko: "조리 순서",
        steps_en: "Steps",
        steps_de: "Kochschritte",
        generating_message: "독일 마트 재료 기반 레시피를 생성 중입니다. 잠시만 기다려주세요...",
        success_message: "새로운 독일 마트 한식 레시피가 성공적으로 생성되었습니다.",
        save_button: "레시피 저장",
        saved_button: "저장됨 ✅",
        all_steps_title: "전체 언어 조리 순서 (All Language Steps)",
        price_title: "한국 식품 품목별 최저가",
        price_subtitle: "주요 품목의 실시간 최저가 정보를 확인하세요.",
        last_update: "최근 업데이트",
        coffee_title: "여러분의 장바구니 물가를 덜어드리는 Kfoodtracker입니다.",
        coffee_desc: "보내주시는 따뜻한 커피 한 잔은 서버 유지비에 크나큰 힘이 됩니다!",
        coffee_button: "서버비 보태기",
        mart_compare: "개 마트 비교",
        no_price_data: "비교 가능한 데이터가 아직 없습니다.",
        best_price: "최저가",
        foodPlaceholder: "어떤 음식을 찾으세요? 🍲",
        beautyPlaceholder: "지금 가장 핫한 K-Beauty 최저가는? ✨",
        bundle: '번들 / 멀티팩',
        single: '낱개',
    },
    en: {
        name: "English",
        title: "K-Food Helper in Germany",
        subtitle: "Create Korean recipes using ingredients easily found in German supermarkets.",
        prompt_label: "Recipe Idea (e.g., Tofu + Spätzle):",
        recent_title: "Recent Generated Recipes",
        placeholder: "Example: Fusion Kimchi Fried Rice using Bratwurst and Sauerkraut",
        button_loading: "Generating...",
        button_ready: "Generate Recipe 🍚",
        desc_title: "Recipe Description",
        ingredients_title: "Ingredients",
        steps_ko: "Cooking Steps ",
        steps_en: "Steps ",
        steps_de: "Kochschritte ",
        generating_message: "Generating German supermarket-based recipe...",
        success_message: "New German supermarket Korean recipe successfully generated.",
        save_button: "Save Recipe",
        saved_button: "Saved ✅",
        all_steps_title: "All Language Steps (Kochschritte in allen Sprachen)",
        price_title: "Lowest Prices by Item",
        price_subtitle: "Check real-time lowest price information for key items.",
        last_update: "Last Updated",
        coffee_title: "Kfoodtracker, helping you save on your grocery bills.",
        coffee_desc: "A warm cup of coffee is a great help for server maintenance costs!",
        coffee_button: "Keep the Tracker Alive",
        mart_compare: "marts compared",
        no_price_data: "No comparison data available yet.",
        best_price: "Best Price",
        foodPlaceholder: "What are you craving today? 🥘",
        beautyPlaceholder: "Find the hottest K-Beauty deals here! ✨",
        bundle: 'Bundle / Multi Pack',
        single: 'Single',
    },
    de: {
        name: "Deutsch",
        title: "Dein K-Food Helfer",
        subtitle: "Erstellen Sie koreanische Rezepte mit Zutaten, die leicht in deutschen Supermärkten erhältlich sind.",
        prompt_label: "Rezeptidee (z.B. Tofu + Spätzle):",
        recent_title: "Kürzlich erstellte Rezepte",
        placeholder: "Beispiel: Fusion Kimchi-Bratreis mit Wurst und Sauerkraut",
        button_loading: "Wird generiert...",
        button_ready: "Rezept generieren 🍚",
        desc_title: "Rezeptbeschreibung",
        ingredients_title: "Zutaten",
        steps_ko: "Kochschritte",
        steps_en: "Steps",
        steps_de: "Kochschritte",
        generating_message: "Generiere das Rezept basierend auf deutschen Zutaten...",
        success_message: "Neues Koreanisches Rezept (Deutschland-Basis) erfolgreich generiert.",
        save_button: "Rezept speichern",
        saved_button: "Gespeichert ✅",
        all_steps_title: "Kochschritte in allen Sprachen",
        price_title: "Tiefstpreise nach Artikeln",
        price_subtitle: "Prüfen Sie Echtzeit-Tiefstpreis-Informationen für wichtige Artikel.",
        last_update: "Zuletzt aktualisiert",
        coffee_title: "Kfoodtracker, die App, mit der Sie Ihre Lebensmittelkosten senken können",
        coffee_desc: "Ein kleiner Kaffee hilft mir, die Serverkosten zu decken!",
        coffee_button: "Unterstütze den Server-Host",
        mart_compare: "Märkte im Vergleich",
        no_price_data: "Noch keine Vergleichsdaten verfügbar.",
        best_price: "Bester Preis",
        foodPlaceholder: "Welches Gericht suchen Sie? 🍛",
        beautyPlaceholder: "Beste K-Beauty Deals entdecken! ✨",
        bundle: 'Bundle / Multipack',
        single: 'Einzelpack',
    },
};

export const limitMessages = {
        ko: {
            title: "한도 초과",
            limit: "오늘의 레시피 생성 한도를 모두 사용했어요 🍽️\n내일 다시 오시면 더 맛있는 레시피로 도와드릴게요!",
            overloaded: "지금 셰프가 너무 바빠요 🧑‍🍳🔥\n잠시 후 다시 시도해 주세요!",
            button: "확인했습니다"
        },
        en: {
            title: "Limit Reached",
            limit: "Daily recipe limit reached 🍽️\nTry again tomorrow for more delicious recipes!",
            overloaded: "Chef is super busy right now 🧑‍🍳🔥\nPlease try again in a few moments!",
            button: "Got it"
        },
        de: {
            title: "Limit erreicht",
            limit: "Tägliches Rezeptlimit erreicht 🍽️\nVersuchen Sie es morgen erneut für weitere leckere Rezepte!",
            overloaded: "Der Chefkoch ist gerade sehr beschäftigt 🧑‍🍳🔥\nBitte versuchen Sie es in Kürze noch einmal!",
            button: "Verstanden"
        }
    };

export const DELIVERY_INFO = {
    ko: [
        { name: "다와요", info: "60€↑ 무료" },
        { name: "Y-Mart", info: "70€↑ 무료 (최소 30€)" },
        { name: "한독몰", info: "70€↑ 무료 (픽업 5%↓)" },
        { name: "Kocket", info: "49€↑ 무료" },
        { name: "K-shop", info: "70€↑ 무료 (냉동 4.99€)" },
        { name: "JoyBuy", info: "당일 배송 €3.99" },
        { name: "GoAsia", info: "39€↑ 무료" },
    ],
    en: [
        { name: "Dawayo", info: "Free over 60€" },
        { name: "Y-Mart", info: "Free over 70€ (Min. 30€)" },
        { name: "Handokmall", info: "Free over 70€ (Pickup 5%↓)" },
        { name: "Kocket", info: "Free over 49€" },
        { name: "K-shop", info: "Free over 70€ (Frozen 4.99€)" },
        { name: "JoyBuy", info: "Same day delivery €3.99" },
        { name: "GoAsia", info: "Free over 39€" },
    ],
    de: [
        { name: "Dawayo", info: "Gratis ab 60€" },
        { name: "Y-Mart", info: "Gratis ab 70€ (Min. 30€)" },
        { name: "Handokmall", info: "Gratis ab 70€ (Abholung 5%↓)" },
        { name: "Kocket", info: "Gratis ab 49€" },
        { name: "K-shop", info: "Gratis ab 70€ (Tiefkühl 4.99€)" },
        { name: "JoyBuy", info: "Same Day Lieferung €3.99" },
        { name: "GoAsia", info: "Gratis ab 39€" },
    ]
};

export const FOOD_CATEGORIES = {
    ko: [
        { id: 'all', label: '전체', emoji: '🍱' },
        { id: 'fresh', label: '신선·냉동', emoji: '❄️' },
        { id: 'grain', label: '쌀·면·가루', emoji: '🌾' },
        { id: 'sauce', label: '양념·소스', emoji: '🍯' },
        { id: 'snack', label: '간식·음료', emoji: '🥤' }
    ],
    en: [
        { id: 'all', label: 'All', emoji: '🍱' },
        { id: 'fresh', label: 'Fresh/Frozen', emoji: '❄️' },
        { id: 'grain', label: 'Grain/Flour', emoji: '🌾' },
        { id: 'sauce', label: 'Sauce/Oil', emoji: '🍯' },
        { id: 'snack', label: 'Snack/Drink', emoji: '🥤' }
    ],
    de: [
        { id: 'all', label: 'Alle', emoji: '🍱' },
        { id: 'fresh', label: 'Frisch & Tiefkühl', emoji: '❄️' },
        { id: 'grain', label: 'Reis & Nudeln', emoji: '🌾' },
        { id: 'sauce', label: 'Saucen & Gewürze', emoji: '🍯' },
        { id: 'snack', label: 'Snacks & Getränke', emoji: '🥤' }
    ], 
}